version: "3.7"

services:
  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "80443:443"
      - "80443:443/udp"
    volumes:
      - etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/www/derek:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared_network

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  shared_network:
    name: shared_network
    external: true