version: '2.4'

services:

  frontend:
    image: "grocy/frontend:v4.0.0"
    build:
      args:
        GROCY_VERSION: v4.0.0
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '127.0.0.1:${HOST_PORT}:8080'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v4.0.0"
    build:
      args:
        GROCY_VERSION: v4.0.0
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    environment:
      - GROCY_MODE=production
      - GROCY_CULTURE=en
      # PHP Environment variables
      - MAX_UPLOAD=50M
      - PHP_MAX_FILE_UPLOAD=200
      - PHP_MAX_POST=100M
      - PHP_MEMORY_LIMIT=512M
    restart: unless-stopped

volumes:
  app-db: