---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.5
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - heimdall_config:/config
    ports:
      - ${HOST_PORT}:80
    restart: unless-stopped
volumes:
  heimdall_config: