version: '3'

services:
  koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
      - ${HOST_PORT}:80
    environment:
      - PHP_TZ=${PHP_TZ}
      - DB_DRIVER=${DB_DRIVER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_VERSION=${DB_VERSION}
    depends_on:
      - db
    volumes:
      - ./volumes/koillection/uploads:/uploads

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./volumes/postgresql:/var/lib/postgresql/data"