version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - "${HOST_PORT}:9090"
    volumes:
      - linkding_data:/etc/linkding/data
    restart: unless-stopped
volumes:
  linkding_data: