version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - "${HOST_PORT}:9090"
    volumes:
      - "${HOST_DATA_DIR:-./data}:/etc/linkding/data"
    restart: unless-stopped